# Generated by Django 6.0.1 on 2026-01-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bundle_posting_forecast_output_issuereport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('consumer', 'Consumer'), ('seller', 'Seller')], max_length=10),
        ),
    ]
