# Generated by Django 6.0.1 on 2026-02-01 22:10

import datetime
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle_posting',
            name='allergen_celery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bundle_posting',
            name='allergen_crustacean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bundle_posting',
            name='allergen_dairy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bundle_posting',
            name='allergen_egg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bundle_posting',
            name='allergen_fish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bundle_posting',
            name='allergen_gluten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bundle_posting',
            name='allergen_lupin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bundle_posting',
            name='allergen_mollusc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bundle_posting',
            name='allergen_mustard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bundle_posting',
            name='allergen_nut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bundle_posting',
            name='allergen_peanut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bundle_posting',
            name='allergen_sesame',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bundle_posting',
            name='allergen_soya',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bundle_posting',
            name='allergen_sulphite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bundle_posting',
            name='category',
            field=models.CharField(default='Food', max_length=100),
        ),
        migrations.AddField(
            model_name='bundle_posting',
            name='creation_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bundle_posting',
            name='pickup_window_end',
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
        migrations.AddField(
            model_name='bundle_posting',
            name='pickup_window_start',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='bundle_posting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='bundle_posting',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bundle_posting',
            name='seller',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.seller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecast_output',
            name='confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forecast_output',
            name='posting',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.bundle_posting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecast_output',
            name='predicted_no_show_prob',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forecast_output',
            name='predicted_reservations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forecast_output',
            name='rationale',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='forecast_output',
            name='time_recommendation',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecast_output',
            name='type',
            field=models.CharField(default='Linear Regression', max_length=100),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='consumer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.consumer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuereport',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='posting',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.bundle_posting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuereport',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Acknowledged'), ('R', 'Resolved')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='type',
            field=models.CharField(choices=[('C', 'collection'), ('A', 'Additional information'), ('S', 'Seller')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='claim_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='consumer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.consumer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='posting',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.bundle_posting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('C', 'collected'), ('N', 'No Show'), ('R', 'Reserved'), ('E', 'Expired')], default='R', max_length=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time_stamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='seller',
            name='closing_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AlterField(
            model_name='seller',
            name='opening_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
