# Generated by Django 6.0.1 on 2026-02-03 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_remove_seller_display_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consumer",
            name="diplay_name",
        ),
    ]
