# Generated by Django 6.0.1 on 2026-02-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_remove_consumer_diplay_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("C", "Collected"),
                    ("N", "No Show"),
                    ("R", "Reserved"),
                    ("E", "Expired"),
                ],
                default="R",
                max_length=1,
            ),
        ),
    ]
