# Generated by Django 6.0.1 on 2026-02-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_reservation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuereport",
            name="type",
            field=models.CharField(
                choices=[
                    ("C", "Collection"),
                    ("A", "Additional information"),
                    ("S", "Seller"),
                ],
                default="C",
                max_length=1,
            ),
        ),
    ]
