# Generated by Django 6.0.1 on 2026-02-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_issuereport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle_posting',
            name='category',
            field=models.CharField(default='Meals', max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='telephone_number',
            field=models.CharField(default='441392661000', max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='website_url',
            field=models.URLField(default='https://www.exeter.ac.uk/'),
        ),
    ]
