# Generated by Django 6.0.1 on 2026-03-09 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_bundle_posting_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle_posting_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='bundle_posting',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bundle_posting_category'),
        ),
    ]
