# Generated by Django 6.0.1 on 2026-03-09 16:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_bundle_posting_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('M', 'Meals'), ('B&P', 'Bread & Pastries'), ('G', 'Groceries'), ('F&P', 'Flowers & Plants'), ('PF', 'Pet Food'), ('V', 'Vegetarian'), ('VE', 'Vegan')], default='M', max_length=5)),
                ('time_stamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('IPD', 'Increased Production'), ('RPD', 'Reduced Production'), ('IPR', 'Increased Price'), ('RPR', 'Reduces Price'), ('O', 'Other')], default='RPD', max_length=5)),
                ('details', models.CharField(blank=True, max_length=1000)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.seller')),
            ],
        ),
    ]
