# Generated by Django 6.0.1 on 2026-03-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_bundle_posting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='wheelchair',
            field=models.BooleanField(default=False),
        ),
    ]
