# Generated by Django 6.0.1 on 2026-03-09 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_bundle_posting_category_and_more'),
        ('main', '0012_seller_actions'),
    ]

    operations = [
    ]
