# Generated by Django 6.0.1 on 2026-03-09 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_merge_20260309_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_actions',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bundle_posting_category'),
        ),
    ]
