# Generated by Django 6.0.1 on 2026-03-10 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_seller_wheelchair'),
        ('main', '0014_alter_seller_actions_category'),
    ]

    operations = [
    ]
